
image: gitpod/workspace-full:latest

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Init
    init: rustup update && go install github.com/go-task/task/v3/cmd/task@latest

vscode:
  extensions:
    - rust-lang.rust-analyzer
